### ISSUE TITLE
Data collector pops exception

### ISSUE THREAD

**Issue by masonwan** [masonwan/tweentiment#1]
Exception on Line 27 of WordWeight.java.

Detailed output

```
happy weight: 0.80654895
jsonTxt:  {"mood":"negative","text":"sad","prob":0.920984729039663}
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/NestableRuntimeException
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.sentiment.weight.WordWeight.getWordWeight(WordWeight.java:27)
    at com.sentiment.file.SentimentFileImpl.getWeight(SentimentFileImpl.java:60)
    at com.sentiment.test.FileMain.main(FileMain.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.exception.NestableRuntimeException
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more
ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2
JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [../../../src/share/back/util.c:838]
```

**Comment by anushaML** [comment]
Might be your JVM issue, the project I sent you works fine on mine.

On Sun, Oct 21, 2012 at 3:11 AM, Mason Wan notifications@github.com wrote:

> Exception on Line 27 of WordWeight.java.
> 
> Detailed output
> 
> happy weight: 0.80654895
> jsonTxt:  {"mood":"negative","text":"sad","prob":0.920984729039663}
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/NestableRuntimeException
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(Unknown Source)
>     at java.security.SecureClassLoader.defineClass(Unknown Source)
>     at java.net.URLClassLoader.defineClass(Unknown Source)
>     at java.net.URLClassLoader.access$100(Unknown Source)
>     at java.net.URLClassLoader$1.run(Unknown Source)
>     at java.net.URLClassLoader$1.run(Unknown Source)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at com.sentiment.weight.WordWeight.getWordWeight(WordWeight.java:27)
>     at com.sentiment.file.SentimentFileImpl.getWeight(SentimentFileImpl.java:60)
>     at com.sentiment.test.FileMain.main(FileMain.java:33)
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.exception.NestableRuntimeException
>     at java.net.URLClassLoader$1.run(Unknown Source)
>     at java.net.URLClassLoader$1.run(Unknown Source)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     ... 15 more
> ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2
> JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [../../../src/share/back/util.c:838]
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/masonaxcte/cmpe239/issues/1.

## 

Lakshmi Anusha Mallampati

**Comment by masonwan** [comment]
You used absolute path for third-party libraries which made it impossible to be run on others' computer. Please list all libraries you used for the data collector.

According to [Json-lib](http://json-lib.sourceforge.net/), there are several dependencies required. Could you pull and fix the dependency or link me to the libraries?

**Comment by masonwan** [comment]
It's actually caused by not installing Maven for Eclipse. To solve the problem, please install Maven in your Eclipse IDE.
